server {
    listen 80;
    server_name nemotours.duckdns.org;

    root /var/www/html/public;
    index index.php;

    client_max_body_size 100M;

    location ^~ /storage/app/public/ {
        alias /var/www/html/storage/app/public/;
        try_files $uri =404;
        access_log off;
        log_not_found off;
        expires 30d;
    }

    location ^~ /storage/ {
        alias /var/www/html/storage/app/public/;
        try_files $uri =404;
        access_log off;
        log_not_found off;
        expires 30d;
    }

    location ^~ /public/ {
        alias /var/www/html/public/;
        try_files $uri $uri/ =404;
        access_log off;
        log_not_found off;
        expires 30d;
    }

    location ~* \.(?:css|js|png|jpg|jpeg|gif|ico|svg|woff2?|eot|ttf|otf|mp4|webp|json|xml)$ {
        root /var/www/html/public;
        try_files $uri =404;
        access_log off;
        log_not_found off;
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass nemotours_app_dev:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
